title: Service
fields:
  -
    handle: image
    field:
      max_files: 1
      mode: list
      container: assets
      folder: service
      restrict: false
      allow_uploads: true
      show_filename: true
      show_set_alt: true
      type: assets
      display: Image
      icon: assets
      localizable: false
      listable: hidden
      instructions_position: above
      visibility: visible
      replicator_preview: true
      hide_display: false
  -
    handle: service_title
    field:
      input_type: text
      antlers: false
      type: text
      display: Title
      icon: text
      localizable: false
      listable: hidden
      instructions_position: above
      visibility: visible
      replicator_preview: true
      hide_display: false
      validate:
        - required
  -
    handle: service_text
    field:
      buttons:
        - bold
        - italic
        - unorderedlist
        - removeformat
        - anchor
      smart_typography: false
      save_html: false
      inline: false
      toolbar_mode: floating
      reading_time: false
      word_count: false
      fullscreen: true
      allow_source: true
      enable_input_rules: true
      enable_paste_rules: true
      remove_empty_nodes: true
      antlers: false
      link_noopener: false
      link_noreferrer: false
      target_blank: false
      always_show_set_button: false
      collapse: false
      previews: true
      type: bard
      display: Text
      icon: bard
      localizable: false
      listable: hidden
      instructions_position: above
      visibility: visible
      replicator_preview: true
      hide_display: false
