title: Settings
fields:
  -
    handle: template
    field:
      hide_partials: true
      blueprint: false
      type: template
      display: Template
      icon: template
      localizable: false
      listable: hidden
      instructions_position: above
      visibility: visible
      replicator_preview: true
      hide_display: false
  -
    handle: layout
    field:
      hide_partials: true
      blueprint: false
      type: template
      display: Layout
      icon: template
      localizable: false
      listable: hidden
      instructions_position: above
      visibility: visible
      replicator_preview: true
      hide_display: false
